name: Deploy assets to AWS S3

on:
  workflow_call:
    inputs:
      bucket:
        required: false
        type: string
        default: answers
      directory:
        required: true
        type: string
      cache-control:
        required: false
        type: string
        default: no-cache

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download build-output artifact
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: dist/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://assets.sitescdn.net/${{ inputs.bucket }}/${{ inputs.directory }} \
          --acl public-read \
          --cache-control ${{ inputs.cache-control }} \
          --profile production