name: Deploy assets to AWS S3 and GCP Cloud Storage

on:
  workflow_call:
    inputs:
      bucket:
        required: false
        type: string
        default: answers
      directory:
        required: true
        type: string
      cache-control:
        required: false
        type: string
        default: no-cache
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GCP_SA_KEY:
        required: true

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build-output artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          aws s3 cp ./dist/ s3://assets.sitescdn.net/${{ inputs.bucket }}/${{ inputs.directory }} \
          --acl public-read \
          --recursive \
          --cache-control ${{ inputs.cache-control }}

  deploy-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build-output artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist/
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Deploy to GCP Bucket
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: dist/
          parent: false
          destination: assets-eu.sitescdn.net/${{ inputs.bucket }}/${{ inputs.directory }}
          headers: |-
            cache-control: ${{ inputs.cache-control }}
