name: Deploy assets to AWS S3 and GCP Cloud Storage

on:
  workflow_call:
    inputs:
      bucket:
        required: false
        type: string
        default: answers
      directory:
        required: true
        type: string
      cache-control:
        required: false
        type: string
        default: no-cache
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build-output-US artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output-US
          path: dist/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: |
          aws s3 cp ./dist/ s3://assets.sitescdn.net/"$BUCKET"/"$DIRECTORY" \
          --acl public-read \
          --recursive \
          --cache-control "CACHE_CONTROL"
        env:
          BUCKET: ${{ inputs.bucket }}
          DIRECTORY: ${{ inputs.directory }}
          CACHE_CONTROL: ${{ inputs.cache-control }}
